json.id @story.id
json.title @story.title
json.body @story.body
json.author @story.author.username
json.image_url @story.image_url
json.description @story.author.description
json.avatar_url @story.author.avatar_url
json.comments @story.comments
json.author_id @story.author.id
